skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrowq32026 = "u6KexT8KmdzPs1uzd2sRDfKr4V5ZTT2GSSku4n7fEWS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
